package com.panfeng.shining.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseThemeBase<M extends BaseThemeBase<M>> extends Model<M> implements IBean {

	public void setThId(java.lang.Long thId) {
		set("th_id", thId);
	}

	public java.lang.Long getThId() {
		return get("th_id");
	}

	public void setThName(java.lang.String thName) {
		set("th_name", thName);
	}

	public java.lang.String getThName() {
		return get("th_name");
	}

	public void setThLntroduction(java.lang.String thLntroduction) {
		set("th_lntroduction", thLntroduction);
	}

	public java.lang.String getThLntroduction() {
		return get("th_lntroduction");
	}

	public void setThSort(java.lang.Integer thSort) {
		set("th_sort", thSort);
	}

	public java.lang.Integer getThSort() {
		return get("th_sort");
	}

	public void setThImage(java.lang.String thImage) {
		set("th_image", thImage);
	}

	public java.lang.String getThImage() {
		return get("th_image");
	}

	public void setThThemeZip(java.lang.String thThemeZip) {
		set("th_theme_zip", thThemeZip);
	}

	public java.lang.String getThThemeZip() {
		return get("th_theme_zip");
	}

	public void setThAuthor(java.lang.String thAuthor) {
		set("th_author", thAuthor);
	}

	public java.lang.String getThAuthor() {
		return get("th_author");
	}

	public void setThMd5(java.lang.String thMd5) {
		set("th_md5", thMd5);
	}

	public java.lang.String getThMd5() {
		return get("th_md5");
	}

	public void setThState(java.lang.Integer thState) {
		set("th_state", thState);
	}

	public java.lang.Integer getThState() {
		return get("th_state");
	}

	public void setThPrice(java.lang.Long thPrice) {
		set("th_price", thPrice);
	}

	public java.lang.Long getThPrice() {
		return get("th_price");
	}

}
