package com.panfeng.shining.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMediaSortList<M extends BaseMediaSortList<M>> extends Model<M> implements IBean {

	public void setMsId(java.lang.Long msId) {
		set("ms_id", msId);
	}

	public java.lang.Long getMsId() {
		return get("ms_id");
	}

	public void setMsName(java.lang.String msName) {
		set("ms_name", msName);
	}

	public java.lang.String getMsName() {
		return get("ms_name");
	}

	public void setMsState(java.lang.Long msState) {
		set("ms_state", msState);
	}

	public java.lang.Long getMsState() {
		return get("ms_state");
	}

	public void setMsChangimageurl(java.lang.String msChangimageurl) {
		set("ms_changimageurl", msChangimageurl);
	}

	public java.lang.String getMsChangimageurl() {
		return get("ms_changimageurl");
	}

	public void setMsLueimageurl(java.lang.String msLueimageurl) {
		set("ms_lueimageurl", msLueimageurl);
	}

	public java.lang.String getMsLueimageurl() {
		return get("ms_lueimageurl");
	}

	public void setMsRemark(java.lang.String msRemark) {
		set("ms_remark", msRemark);
	}

	public java.lang.String getMsRemark() {
		return get("ms_remark");
	}

}
