package com.panfeng.shining.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserInfo<M extends BaseUserInfo<M>> extends Model<M> implements IBean {

	public void setUiId(java.lang.Integer uiId) {
		set("ui_id", uiId);
	}

	public java.lang.Integer getUiId() {
		return get("ui_id");
	}

	public void setUiImei(java.lang.String uiImei) {
		set("ui_imei", uiImei);
	}

	public java.lang.String getUiImei() {
		return get("ui_imei");
	}

	public void setUiUuid(java.lang.String uiUuid) {
		set("ui_uuid", uiUuid);
	}

	public java.lang.String getUiUuid() {
		return get("ui_uuid");
	}

	public void setUiName(java.lang.String uiName) {
		set("ui_name", uiName);
	}

	public java.lang.String getUiName() {
		return get("ui_name");
	}

	public void setUiPhone(java.lang.String uiPhone) {
		set("ui_phone", uiPhone);
	}

	public java.lang.String getUiPhone() {
		return get("ui_phone");
	}

	public void setUiMbId(java.lang.Integer uiMbId) {
		set("ui_mb_id", uiMbId);
	}

	public java.lang.Integer getUiMbId() {
		return get("ui_mb_id");
	}

	public void setUiImage(java.lang.String uiImage) {
		set("ui_image", uiImage);
	}

	public java.lang.String getUiImage() {
		return get("ui_image");
	}

	public void setUiMonies(java.lang.Long uiMonies) {
		set("ui_monies", uiMonies);
	}

	public java.lang.Long getUiMonies() {
		return get("ui_monies");
	}

	public void setUiAuthcode(java.lang.String uiAuthcode) {
		set("ui_authcode", uiAuthcode);
	}

	public java.lang.String getUiAuthcode() {
		return get("ui_authcode");
	}

}
