package com.panfeng.shining.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMediaBase<M extends BaseMediaBase<M>> extends Model<M> implements IBean {

	public void setMbId(java.lang.Integer mbId) {
		set("mb_id", mbId);
	}

	public java.lang.Integer getMbId() {
		return get("mb_id");
	}

	public void setMbVideoName(java.lang.String mbVideoName) {
		set("mb_video_name", mbVideoName);
	}

	public java.lang.String getMbVideoName() {
		return get("mb_video_name");
	}

	public void setMbName(java.lang.String mbName) {
		set("mb_name", mbName);
	}

	public java.lang.String getMbName() {
		return get("mb_name");
	}

	public void setMbContent(java.lang.String mbContent) {
		set("mb_content", mbContent);
	}

	public java.lang.String getMbContent() {
		return get("mb_content");
	}

	public void setMbKeys(java.lang.String mbKeys) {
		set("mb_keys", mbKeys);
	}

	public java.lang.String getMbKeys() {
		return get("mb_keys");
	}

	public void setMbUploadTime(java.lang.String mbUploadTime) {
		set("mb_upload_time", mbUploadTime);
	}

	public java.lang.String getMbUploadTime() {
		return get("mb_upload_time");
	}

	public void setMbWeight(java.lang.Integer mbWeight) {
		set("mb_weight", mbWeight);
	}

	public java.lang.Integer getMbWeight() {
		return get("mb_weight");
	}

	public void setMbState(java.lang.Long mbState) {
		set("mb_state", mbState);
	}

	public java.lang.Long getMbState() {
		return get("mb_state");
	}

	public void setMbAuthor(java.lang.String mbAuthor) {
		set("mb_author", mbAuthor);
	}

	public java.lang.String getMbAuthor() {
		return get("mb_author");
	}

	public void setMbFavorite(java.lang.Integer mbFavorite) {
		set("mb_favorite", mbFavorite);
	}

	public java.lang.Integer getMbFavorite() {
		return get("mb_favorite");
	}

	public void setMbSettingtimes(java.lang.Integer mbSettingtimes) {
		set("mb_settingtimes", mbSettingtimes);
	}

	public java.lang.Integer getMbSettingtimes() {
		return get("mb_settingtimes");
	}

	public void setMbPlays(java.lang.Integer mbPlays) {
		set("mb_plays", mbPlays);
	}

	public java.lang.Integer getMbPlays() {
		return get("mb_plays");
	}

	public void setMbMd5(java.lang.String mbMd5) {
		set("mb_md5", mbMd5);
	}

	public java.lang.String getMbMd5() {
		return get("mb_md5");
	}

	public void setMbPrice(java.lang.Long mbPrice) {
		set("mb_price", mbPrice);
	}

	public java.lang.Long getMbPrice() {
		return get("mb_price");
	}

}
