package com.panfeng.shining.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * 
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("audio_base_list", "id", AudioBaseList.class);
		arp.addMapping("audio_sort_list", "id", AudioSortList.class);
		arp.addMapping("loadboot", "lead_id", Loadboot.class);
		arp.addMapping("media_base", "mb_id", MediaBase.class);
		arp.addMapping("media_base_user", "id", MediaBaseUser.class);
		arp.addMapping("media_sort_list", "ms_id", MediaSortList.class);
		arp.addMapping("message", "mg_id", Message.class);
		arp.addMapping("purchase_history", PurchaseHistory.class);
		arp.addMapping("theme_base", "th_id", ThemeBase.class);
		arp.addMapping("user_info", "ui_id", UserInfo.class);
	}
}
