package com.panfeng.shining.model;

import com.panfeng.shining.model.base.BaseAudioBaseList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AudioBaseList extends BaseAudioBaseList<AudioBaseList> {
	public static final AudioBaseList dao = new AudioBaseList();
}
