package com.panfeng.shining.model;

import com.panfeng.shining.model.base.BaseAudioSortList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AudioSortList extends BaseAudioSortList<AudioSortList> {
	public static final AudioSortList dao = new AudioSortList();
}
