package com.panfeng.shining.model;

import com.panfeng.shining.model.base.BaseLoadboot;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Loadboot extends BaseLoadboot<Loadboot> {
	public static final Loadboot dao = new Loadboot();
}
