package com.panfeng.shining.model;

import com.panfeng.shining.model.base.BaseMediaSortList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MediaSortList extends BaseMediaSortList<MediaSortList> {
	public static final MediaSortList dao = new MediaSortList();
}
