package com.panfeng.shining.model;

import com.panfeng.shining.model.base.BaseMediaBase;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MediaBase extends BaseMediaBase<MediaBase> {
	public static final MediaBase dao = new MediaBase();
}
