package com.panfeng.shining.model;

import com.panfeng.shining.model.base.BaseMediaBaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MediaBaseUser extends BaseMediaBaseUser<MediaBaseUser> {
	public static final MediaBaseUser dao = new MediaBaseUser();
}
