package com.panfeng.shining.model;

import com.panfeng.shining.model.base.BaseMessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Message extends BaseMessage<Message> {
	public static final Message dao = new Message();
}
