package com.panfeng.shining.model;

import com.panfeng.shining.model.base.BasePurchaseHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PurchaseHistory extends BasePurchaseHistory<PurchaseHistory> {
	public static final PurchaseHistory dao = new PurchaseHistory();
	
}
