package com.panfeng.shining.model;

import com.panfeng.shining.model.base.BaseThemeBase;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ThemeBase extends BaseThemeBase<ThemeBase> {
	public static final ThemeBase dao = new ThemeBase();
}
